FROM node:20

# Enable pnpm via corepack
RUN corepack enable && corepack prepare pnpm@latest --activate

WORKDIR /usr/src/app

COPY package.json ./
COPY tsconfig.json ./
COPY next.config.js ./

RUN pnpm install

# Copy source (will be overridden by volume in dev)
COPY app ./app

ENV NODE_ENV=development
ENV NEXT_PUBLIC_APP_ENV=dev
ENV PORT=3000

EXPOSE 3000

CMD ["pnpm", "dev"]
